### ISSUE TITLE
Bug: Tooltip doesn't show'This day is not clickable' on inactive days

### ISSUE THREAD

**Issue by farhatamannaislam** [Jamie-Gargrave/magic-calendar#75]

**Comment by Morgana-S** [comment]
This is caused by the 'disabled' class having 'pointer-events: none' as a property. Removing 'pointer-events: none' and keeping 'cursor: not allowed' should fix this issue while still indicating to the user that the button isn't clickable.

**Comment by Morgana-S** [comment]
Bug has been fixed - implementation of all days means this issue has been depreciated.
